name: Bot Instagram Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

permissions:
  contents: write         # Permiso para guardar el archivo json

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: |
        pip install -r requirements.txt

    - name: Correr el Bot
      run: |
        python monitor.py

    - name: Guardar cambios (JSON)
      run: |
        git config --global user.name 'Bot GitHub'
        git config --global user.email 'bot@noreply.github.com'
        git add historial_multi.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar datos" && git push)
        
